apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikehopper-ui-deployment
  labels:
    app: bikehopper-ui
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bikehopper-ui
  template:
    metadata:
      labels:
        app: bikehopper-ui
    spec:
      containers:
        - name: bikehopper-ui
          image: ghcr.io/bikehopper/bikehopper-ui@sha256:d0498aafec56eaefebd312f069ea8cc05feacaa04b2268e0e7b5f42892d7df23
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          readinessProbe:
            httpGet:
              path: /health.html
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 10
      imagePullSecrets:
        - name: dockerconfigjson-github-com
